[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[profile.default.fuzz]
include_storage = false
runs = 10000

[fmt]
line_length = 120
tab_width = 4
int_types = "long"
multiline_func_header = "attributes_first"
quote_style = "double"
number_underscore = "thousands"
override_spacing = true
wrap_comments = false
