name: Format, Snapshot

on:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.JG_PAT_EXP_11_14_24 }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: yarn

      - uses: foundry-rs/foundry-toolchain@v1

      - name: Format
        run: forge fmt

      - name: Snapshot
        run: forge snapshot

      - name: Test
        run: forge test -vvv

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore(bot): format & snapshot'
